import type { OrderRow } from "@/types/order";

/** Seed data matching the brief's example — shown before any upload. */
export const SAMPLE_ORDERS: OrderRow[] = [
  {
    id: "1001",
    date: new Date("2024-03-09"),
    customer: "Ruby Curd",
    category: "Mobiles",
    qty: 2,
    unitPrice: 900,
    amount: 1800,
    channel: "Web",
    status: "Shipped",
  },
  {
    id: "1002",
    date: new Date("2024-03-15"),
    customer: "Will Johnson",
    category: "Tablets",
    qty: 1,
    unitPrice: 700,
    amount: 700,
    channel: "Mobile App",
    status: "Delivered",
  },
  {
    id: "1003",
    date: new Date("2024-03-18"),
    customer: "Bobby Gray",
    category: "Televisions",
    qty: 3,
    unitPrice: 1500,
    amount: 4200,
    channel: "In-Store",
    status: "Pending",
  },
  {
    id: "1004",
    date: new Date("2024-03-27"),
    customer: "Robert C.",
    category: "Laptops",
    qty: 2,
    unitPrice: 2000,
    amount: 4000,
    channel: "Web",
    status: "Shipped",
  },
  {
    id: "1005",
    date: new Date("2024-04-01"),
    customer: "Steven G.",
    category: "Mobiles",
    qty: 1,
    unitPrice: 950,
    amount: 950,
    channel: "Mobile App",
    status: "Pending",
  },
  {
    id: "1006",
    date: new Date("2024-04-04"),
    customer: "Maria Lopez",
    category: "Tablets",
    qty: 4,
    unitPrice: 650,
    amount: 2500,
    channel: "Web",
    status: "Delivered",
  },
  {
    id: "1007",
    date: new Date("2024-04-09"),
    customer: "Chen Wei",
    category: "Laptops",
    qty: 1,
    unitPrice: 1800,
    amount: 1750,
    channel: "In-Store",
    status: "Shipped",
  },
  {
    id: "1008",
    date: new Date("2024-04-12"),
    customer: "Anita Desai",
    category: "Televisions",
    qty: 2,
    unitPrice: 1200,
    amount: 2400,
    channel: "Web",
    status: "Delivered",
  },
  {
    id: "1009",
    date: new Date("2024-04-15"),
    customer: "Tom Becker",
    category: "Mobiles",
    qty: 5,
    unitPrice: 800,
    amount: 3950,
    channel: "Mobile App",
    status: "Pending",
  },
  {
    id: "1010",
    date: new Date("2024-04-20"),
    customer: "Sara Khan",
    category: "Laptops",
    qty: 1,
    unitPrice: 2200,
    amount: 2200,
    channel: "Web",
    status: "Shipped",
  },
];
